# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='movie_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
