# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0002_auto_20180618_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_details',
            old_name='direcor_name',
            new_name='director_name',
        ),
    ]
